### ISSUE TITLE
Support of the pre-es2015 browsers

### ISSUE THREAD

**Issue by ValeriiVasin** [npm/semver.npmjs.com#14]
Currently in safari i do see an error in console: 

```
bundle.js:1245SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
```

And seems this is added by Heroku or so, because local version of the bundle does not contain the constant and is working fine.

![screenshot](http://i.imgur.com/aKZyXFf.gif)

**Comment by ashleygwilliams** [comment]
this is fixed on staging: https://semver.npm.red

fixed by #16 pushing to production imminently
