### ISSUE TITLE
Can't load data on Firefox ESR

### ISSUE THREAD

**Issue by steveklabnik** [npm/semver.npmjs.com#15]
Firefox 45.3.0 ESR here, semver.npmjs.com no longer shows any versions. I have this in my console:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://npm-registry-cors-proxy.herokuapp.com/lodash. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by ashleygwilliams** [comment]
fixed by #16 , deploying to production imminently

**Comment by steveklabnik** [comment]
:confetti_ball:
