### ISSUE TITLE
doesn't work with namespaced packages

### ISSUE THREAD

**Issue by gdi2290** [npm/semver.npmjs.com#9]
![screen shot 2016-05-13 at 2 06 56 pm](https://cloud.githubusercontent.com/assets/1016365/15261970/5aebbe22-1914-11e6-9f55-a0f7a3ec8918.jpg)

**Comment by devrelm** [comment]
@gdi2290 This can be closed. PR's #18, #19, and #21 were put in to fix this, and #21 was ultimately merged ~10 months ago.

**Comment by gdi2290** [comment]
koo
